### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by verata-veritatis** [verata-veritatis/pybit#1]
@all-contributors please add @verata-veritatis for code

**Comment by tconley** [comment]
@all-contributors please add @tconley for code

**Comment by tconley** [comment]
@all-contributors please add @verata-veritatis for code

**Comment by verata-veritatis** [comment]
@all-contributors add @verata-veritatis for docs

**Comment by verata-veritatis** [comment]
@all-contributors add @tconley for ideas

**Comment by verata-veritatis** [comment]
@all-contributors add @tconley for ideas
