### ISSUE TITLE
New APIs released by bybit can you please modify it in the code. 

### ISSUE THREAD

**Issue by HeshamMahrous** [verata-veritatis/pybit#10]
1. The following WebSocket topics will be removed from service:

a) orderBook25 (please replace with topic orderBookL2_25 or

orderBook_200.100ms)

b) kline (please replace with topic klineV2)

c) instrument (please replace with topic instrument_info)

2. The following REST API will be upgraded. The older version of API will be deprecated on December 10, 2020. Effective immediately, the rate limit will be reduced by half before being completely removed from service on December 17, 2020. Hence, please use the following new REST API endpoints:

a) /open-api/order/list (please replace with /v2/private/order/list)

b) /open-api/stop-order/create (please replace with /v2/private/stop-order/create)

c) /open-api/stop-order/list (please replace with /v2/private/stop-order/list)

d) /open-api/stop-order/cancel (please replace with /v2/private/stop-order/cancel)

e) /open-api/order/replace (please replace with /v2/private/order/replace)

f) /open-api/stop-order/replace (please replace with /v2/private/stop-order/replace)

g) /open-api/order/create (please replace with /v2/private/order/create)

h) /open-api/order/cancel (please replace with /v2/private/order/cancel)

i) /position/list (please replace with /v2/private/position/list)

j) /user/leverage (please replace with /v2/private/position/list)

**Comment by verata-veritatis** [comment]
Hi @HeshamMahrous,

Yes, I am currently working on various updates to the library and will push the new endpoints with the rest of the updates for the next version. As far as WebSocket, the user defines his/her own topics when subscribing (i.e. the topics aren't hardcoded into the lib).

**Comment by verata-veritatis** [comment]
New endpoint URLs are up.
https://github.com/verata-veritatis/pybit/commit/896f2b13b10aefdd6743e22b34fba472e0b11b19
