### ISSUE TITLE
malloc: can't allocate region

### ISSUE THREAD

**Issue by rnnyrk** [verata-veritatis/pybit#13]
Hi there,

I have pybit v1.1.8 installed in my virtual environment. When I try to run my app I get the following error:

```
python data.py 
python(2411,0x112488e00) malloc: can't allocate region
:*** mach_vm_map(size=18446744071964418048, flags: 100) failed (error code=3)
python(2411,0x112488e00) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Traceback (most recent call last):
  File "/Users/rr/Developer/Python/bybit/data.py", line 1, in <module>
    from classes.Client import Client
  File "/Users/rr/Developer/Python/bybit/classes/Client.py", line 2, in <module>
    from pybit import WebSocket
  File "/Users/rr/Developer/Python/bybit/env/lib/python3.9/site-packages/pybit/__init__.py", line 24, in <module>
    import websocket
  File "/Users/rr/Developer/Python/bybit/env/lib/python3.9/site-packages/websocket/__init__.py", line 22, in <module>
    from ._abnf import *
  File "/Users/rr/Developer/Python/bybit/env/lib/python3.9/site-packages/websocket/_abnf.py", line 34, in <module>
    import numpy
  File "/Users/rr/Developer/Python/bybit/env/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```

My data.py has the following code. When I commented line 2 the erorr disappears:
```
import bybit
from pybit import WebSocket
from config import API_KEY, API_SECRET
```

Do you have any idea what the issue can be?
Running python 3.9.0
Thanks for th help.

**Comment by verata-veritatis** [comment]
Hey there,

Did you install python using brew?

From my research it seems like brew is still buggy on Big Sur, and numpy doesn't like the installation. From the error you can see that the exception is popped when websocket library attempts to import numpy.

https://stackoverflow.com/questions/64530174/python3-9-malloc-cant-allocate-region-error-3
https://github.com/numpy/numpy/issues/17557

**Comment by rnnyrk** [comment]
Hi @verata-veritatis. I have python installed with `pyenv` and installed pyenv with brew indeed.  Strange thing is that it actually did work after updating to Big Sur. No clue why it suddenly stopped working. Downgraded `numpy` to 1.18.0 instead of 1.19.x and now it works again. Thanks for your help.
