### ISSUE TITLE
Bug: Param validation for 'from' failed on the 'required' tag

### ISSUE THREAD

**Issue by camhahu** [verata-veritatis/pybit#14]
Just stumbled upon this repo toady, really appreciate everyone's work!

When using `query_kline`, `query_mark_price_kline` on the HTTP class, trying to use `from` in **kwargs will throw a SyntaxError since `from` is a reserved keyword in Python.

Steps to reproduce:

```
import time
from pybit import HTTP

if __name__ == "__main__":
    session = HTTP("https://api.bybit.com")
    session.query_kline(symbol="BTCUSD", interval="1", from=int(time.time()) - 60 * 60)

```

I noticed you've used `from_time` in the tests, but it appears the tests have gone stale. Will make a PR today.

**Comment by camhahu** [comment]
See PR #15

**Comment by verata-veritatis** [comment]
Perfect; I was going to fix this next week but looks like you've got it. The current work around was to simply create a dictionary and send the dictionary through as `**kwargs`. Merging PR. I'll release a new version on pypi this weekend.
