### ISSUE TITLE
Websocket - logger error for 'stop_order_id'

### ISSUE THREAD

**Issue by kitt-th** [verata-veritatis/pybit#20]
Greets,

I'm getting the following error from the logging module when a stoploss order is placed or modified on the testnet. I can only presume that the bybit websocket is passing back 'stop_order_id' as a parameter which is not expected?

ERROR - error from callback <bound method WebSocket._on_message of <pybit.WebSocket object at 0x1a1b442ad0>>: 'stop_order_id'

Conditional order placement and modify orders are working fine for me BTW, the error just appears when orders are sent / modified.

Any idea why this is happening?

Thanks

**Comment by verata-veritatis** [comment]
Duplicate issue: https://github.com/verata-veritatis/pybit/issues/21.
