### ISSUE TITLE
Websocket logger error from callback

### ISSUE THREAD

**Issue by kitt-th** [verata-veritatis/pybit#21]
Greets,

I'm getting the following error from the logging module when a stoploss order is placed or modified on the testnet. I can only presume that the bybit websocket is passing back 'stop_order_id' as a parameter which is not expected?

ERROR - error from callback <bound method WebSocket._on_message of <pybit.WebSocket object at 0x1a1b442ad0>>: 'stop_order_id'

From how I'm reading the docs - it sends back the order id as 'order_id' rather than 'stop_order_id'

Conditional order placement and modify orders are working fine for me BTW, the error just appears when orders are sent / modified.

Any idea why this is happening?

Thanks

**Comment by verata-veritatis** [comment]
Hey there,

I'll take a look today and will let you know.

**Comment by verata-veritatis** [comment]
Hmm I wasn't able to reproduce this on testnet. Would you mind describing how you placed your stop order and what sequence of events led to this error?

**Comment by verata-veritatis** [comment]
I see it now; it seems to happen very sporadically. Give me a few.

**Comment by verata-veritatis** [comment]
Fixed in 77914c7f9d42dce2836bb637227f8cae76b02b95. Will be building new release later today.

**Comment by APF20** [comment]
> Fixed in [77914c7](https://github.com/verata-veritatis/pybit/commit/77914c7f9d42dce2836bb637227f8cae76b02b95). Will be building new release later today.

@verata-veritatis the change implemented in that fix actually breaks the linear websocket feeds, which still do use 'stop_order_id' as the identifier. 

I dont know if this is another change made by Bybit without notification again, as I am sure I checked the change to use "topic+'_id'" against both inverse and linear when I implemented it.

@kitt-th was it working ok before? If so, I will contact Bybit to ask if linear will be changing also, or we will have to implement a workaround for yet another anomaly of field names...

**Comment by verata-veritatis** [comment]
It was working a couple days ago with linear lmao. Sounds like they might have been making some on-the-fly changes?

**Comment by verata-veritatis** [comment]
It was working for a while with 'stop_order_id' but only recently started breaking on the 'stop_order' topic for inverse, so they must've changed it recently.

**Comment by APF20** [comment]
Something isn't right when an exchange makes changes that break things, without notifying anyone in advance, or even after the fact.

Maybe the change to this feed happened when they went offline for 8mins the other day, for 'internal upgrades', without telling anyone? It almost seems like Bybit are basically running a beta version api, but with peoples real money.

I'll see if I can get on to Dexter and get some confirmation of which field name to use going forward for this issue.

**Comment by APF20** [comment]
They confirmed the change to Inverse is permanent and Linear will be changed to also use 'order_id' in the 'future'.

I have implemented a temporary workaround in the latest PR #22, it will have to be updated again when they change the Linear field name too.

**Comment by verata-veritatis** [comment]
Thanks @APF20 for making the workaround. Pushed to master in 1a543301143fa9040a57a8657822ed37eb99c8aa. Will package new release later today.
