### ISSUE TITLE
Query KLine parameter "from"

### ISSUE THREAD

**Issue by devsquaaa** [verata-veritatis/pybit#23]
I don't know how I am supposed to pass the parameter "from" on the query_kline() method, as "from" is a python keyword.

I have tried passing it anyway, and it obviously gives a syntax error:

_File "path/to/file.py", line 19
    session.query_kline(symbol="BTCUSD", interval=interval, from=timestamp)
                                                                                               ^
SyntaxError: invalid syntax_

I am probably missing something, since no one pointed out this issue, so I am hoping someone will help me.

**Comment by devsquaaa** [comment]
My bad.

Should have looked here: https://github.com/verata-veritatis/pybit/blob/master/tests/test_pybit.py

**Comment by verata-veritatis** [comment]
Haha you got it! I'll make this clearer in the README. It's unfortunate that Bybit decided to use `from`, which just happens to be reserved on Python...
