### ISSUE TITLE
Issues with Websocket and Query Parameter "from"

### ISSUE THREAD

**Issue by hfrog713** [verata-veritatis/pybit#26]
When using the from parameter for the query_mark_kline method it is saying that it is invalid syntax. 
I think it is because from is a keyword. 

Also, i noticed the Websocket.md page is no longer maintained. 
Is anyone maintaining that? 
I am getting a Websocket object does not have a send method error. 

Can someone please assist? 
Is this codebase being actively maintained?

**Comment by verata-veritatis** [comment]
@hfrog713 use `from_id`. The method will handle it and submit as `from` to bybit.
