### ISSUE TITLE
Add ByBit Futures support

### ISSUE THREAD

**Issue by tomcru** [verata-veritatis/pybit#27]
e.g. "BTCUSD0625"

Might add if I find the time in the next couple of days.

**Comment by verata-veritatis** [comment]
Thanks Tom. I'll take a look at it as well. Yeah I've been so busy lately haven't had time to update the market maker based on `pybit` at all despite numerous users saying its broken haha.

**Comment by tomcru** [comment]
looks like "/v2/" suffix needs to be replaced with "/futures/" on the affected endpoints when wanting to access the futures symbol "BTCUSDM21".

From what I've tested so far (trade.BTCUSDM21, instrument_info.100ms.BTCUSDM21), the Websocket needs no changes.
