### ISSUE TITLE
Issues with Websocket connection from windows server 2016

### ISSUE THREAD

**Issue by slurpxbt** [verata-veritatis/pybit#28]
below is the error I get when I try to connect to websocket on widows server 2016

the code works fine on my personal PC

ERROR:
2021-03-14 11:28:44 - websocket - ERROR - error from callback <bound method WebSocket._on_message of <pybit.WebSocket object at 0x000002064BE7FE50>>: _on_message() takes 2 positional arguments but 3 were given

**Comment by tomcru** [comment]
I'm randomly running into the same issues (on Ubuntu), but have correct version of websocket-client installed.

Changing the code to this:

```python
self.ws = websocket.WebSocketApp(  
  url=url,
  on_message= lambda ws, msg: self._on_message(msg),
  on_close= self._on_close(),
  on_open= self._on_open(),
  on_error= lambda ws, err: self._on_error(err)
)
```

fixes the issue.

@verata-veritatis any thoughts?
