### ISSUE TITLE
Standard post-only Limit orders on linear USDT being rejected ('reduce_only' test fails!)

### ISSUE THREAD

**Issue by kitt-th** [verata-veritatis/pybit#36]
Greets,
A puzzling problem here - I am hoping it's something small I have missed... if so please let me know!

Trying: send 3 post only limit orders to open a position, using place_active_order_bulk()

As _reduce_only_ is not necessary, or even logical to have in a limit order that would increse a position of 0 to 0.008 BTC if filled - this error makes no sense to me!

The orders being passed to place_active_order_bulk() are:
`[{'symbol': 'BTCUSDT', 'order_type': 'Limit', 'side': 'Buy', 'qty': 0.008, 'price': 45555.0, 'time_in_force': 'PostOnly'}, 
{'symbol': 'BTCUSDT', 'order_type': 'Limit', 'side': 'Buy', 'qty': 0.008, 'price': 44321.0, 'time_in_force': 'PostOnly'}, 
{'symbol': 'BTCUSDT', 'order_type': 'Limit', 'side': 'Buy', 'qty': 0.008, 'price': 43434.0, 'time_in_force': 'PostOnly'}]`

error is:

**Param validation for 'reduce_only' failed on the 'exists' tag (ErrCode: 10001) (ErrTime: 12:46:31).**

**Request → POST https://api-testnet.bybit.com/private/linear/order/create: {'api_key': 'xxxxxxx', 'order_type': 'Limit', 'price': 45555, 'qty': 0.008, 'recv_window': 5000, 'side': 'Buy', 'symbol': 'BTCUSDT', 'time_in_force': 'PostOnly', 'timestamp': 1619786791191, 'sign': 'xxxxxxx'}.**

Any help welcome!

**Comment by kitt-th** [comment]
addendum - the above works fine on the inverse perp BTCUSD pair, 
but not on the BTCUSDT perp pair

**Comment by kitt-th** [comment]
aaaand my mistake for reading the inverse futures docs and not the linear usdt futures docs :D
self-solved

**Comment by only4everock** [comment]
how did you fixed it ? Can you share it please ? Thanks

**Comment by only4everock** [comment]
if I make reduce only true on set tp and close on trigger false on stop not working
