### ISSUE TITLE
WS subscriptions not working (returning empty sets)

### ISSUE THREAD

**Issue by projenix** [verata-veritatis/pybit#46]
Hello,

I'm using the official example as-is and I'm getting "{}" from all subscriptions.

Thanks in advance,

**Comment by To-Life** [comment]
the same issue, @projenix  may I know how to resolve. tks.

**Comment by dextertd** [comment]
@To-Life Please check your code against the examples (in the "examples" folder). If you're still not sure, feel free to share your code. It will be easier to solve if you join the bybit telegram group https://t.me/BybitAPI
