### ISSUE TITLE
get_wallet_balance(spot=True) gives empty results when sub account has no balances

### ISSUE THREAD

**Issue by projenix** [verata-veritatis/pybit#54]
This bug is related to spot sub accounts only.

## How to reproduce:
Make sure the spot section of a sub account has no balances, then try to query its balance with get_wallet_balance(spot=True) using the sub account's API keys. Instead of getting a well formed output showing zero balances you will get the following empty output instead:

{'ret_code': 0, 'ret_msg': '', 'ext_code': None, 'ext_info': None, 'result': {'balances': []}}

**Comment by dextertd** [comment]
Bybit API problem, not isolated to pybit
