### ISSUE TITLE
Parsing Returned Data

### ISSUE THREAD

**Issue by g1thub11** [verata-veritatis/pybit#62]
Could you provide an example of how to parse data for pybit in Python? To get just the order_id from session.get_active_order(symbol="XRPUSDT") what would I need to do?

**Comment by Marcus020** [comment]
Multiple ways of doing that, two examples:

contract_size = session.my_position(symbol="BTCUSD")
print(contract_size["result"]["size"])

contract_size = (session.my_position(symbol="BTCUSD"))["result"]["size"]
print(contract_size)

etc.

Not sure if they have a .result() function like the previous library.
