### ISSUE TITLE
Website: Get risk limit endpoint does not require authentication but Pybit doesn't seem to agree

### ISSUE THREAD

**Issue by viper7882** [verata-veritatis/pybit#65]
There seems to be a mismatch between document @ https://bybit-exchange.github.io/docs/linear/?python--pybit#t-getrisklimit vs actual pybit v1.3.2

Document mentioned Get risk limit. This endpoint does not require authentication but when I run the example Python code below,
```python
from pybit import HTTP
session = HTTP("https://api-testnet.bybit.com")
print(session.get_risk_limit(
    symbol="BTCUSDT"
))
```
authentication is expected:
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "D:\xxx\venv\lib\site-packages\pybit\__init__.py", line 1259, in get_risk_limit
    return self._submit_request(
  File "D:\xxx\venv\lib\site-packages\pybit\__init__.py", line 1734, in _submit_request
    signature = self._auth(
  File "D:\xxx\venv\lib\site-packages\pybit\__init__.py", line 1655, in _auth
    raise PermissionError('Authenticated endpoints require keys.')
PermissionError: Authenticated endpoints require keys.

I trust website is correct whereas Pybit requires fix. Rationale is that Get risk limit is mapped to /public/linear/risk-limit logically should not require authentication.

**Comment by dextertd** [comment]
Good catch. Will fix it.
