### ISSUE TITLE
ws exits with winerror 10054 after certain amout of time 

### ISSUE THREAD

**Issue by LordOberlord** [verata-veritatis/pybit#7]
After ca. 6-12 hours the ws exits automatically with winerror 10054 "An existing connection was forcibly closed by the remote host".
[Log.txt](https://github.com/verata-veritatis/pybit/files/4469700/Log.txt)

**Comment by verata-veritatis** [comment]
The remote host can sometimes close the WebSocket connection. This can be detected by performing `ws.ping()` on interval. If connection has been lost, the request will return an error, which can be caught with an exception and followed by a reconnect. I'm considering adding an `auto_reconnect=True` argument to the WebSocket constructor, which will do all of that automatically `_on_error`.

**Comment by LordOberlord** [comment]
Ok, I will rewrite my script and see what will happen.
Thank you!

**Comment by verata-veritatis** [comment]
The issue seems to be on HTTP and not on WebSockets. I will update so that it handles and retries after error.

**Comment by verata-veritatis** [comment]
WebSockets/HTTP will now force retry after failure. 
https://github.com/verata-veritatis/pybit/commit/368439efbc6db01154b72cbe7986c6356b712562
https://github.com/verata-veritatis/pybit/commit/f3e4ec5941ccd50b5f9539921a2e5371a98be737
