### ISSUE TITLE
Issue: max_leverage of Query Symbol does not change even after risk_id change using set_risk_limit

### ISSUE THREAD

**Issue by viper7882** [verata-veritatis/pybit#73]
Hi Pybit Admin,

It has been discovered that the max_leverage value from Query Symbol always exhibit the highest maximum leverage value despite the set_risk_limit has been switched from lowest Risk ID to highest Risk ID.

```python
import inspect
from pprint import pprint

from pybit import HTTP

bybit_testnet_authentication = {
    'key'     : api_key,
    'secret'  : api_secret
}

def print_symbol_leverage(session_auth):
    '''
    Reference: https://help.bybit.com/hc/en-us/articles/360039749753-Risk-Limit-Inverse-Contract-
    Reference: https://help.bybit.com/hc/en-us/articles/900000170023-Risk-Limit-USDT-Contract-
    Reference: https://bybit-exchange.github.io/docs/inverse/?python#t-querysymbol
    Reference: https://bybit-exchange.github.io/docs/linear/#t-querysymbol
    '''
    response = session_auth.query_symbol(
        symbol=symbol_id
    )

    for result in response['result']:
        if result['name'] != symbol_id:
            continue

        print("symbol_id: {}, leverage_filter:".format(symbol_id))
        pprint(result['leverage_filter'])


if __name__ == "__main__":
    api_key = bybit_testnet_authentication['key']
    api_secret = bybit_testnet_authentication['secret']

    mainnet_url = "https://api.bybit.com"
    testnet_url = "https://api-testnet.bybit.com"

    symbol_name = "UNI/USDT"
    symbol_id = symbol_name.replace("/", "")

    # Unauthenticated
    session_unauth = HTTP(endpoint=testnet_url)

    # Authenticated
    session_auth = HTTP(
        endpoint=testnet_url,
        api_key=api_key,
        api_secret=api_secret,
    )

    response = session_auth.get_risk_limit(
        symbol=symbol_id
    )
    # print("Risk Limit:")
    # pprint(response['result'])

    # for result in response['result']:
    #     print("symbol: {}, risk_id: {}, max_leverage: {}".format(
    #         result['symbol'], result['id'], result['max_leverage']
    #     ))

    min_risk_id = response['result'][0]['id']
    max_risk_id = response['result'][-1]['id']
    print("symbol: {}, min_risk_id: {}, max_risk_id: {}".format(
        symbol_id, min_risk_id, max_risk_id
    ))

    print_symbol_leverage(session_auth)

    '''
    Reference: https://bybit-exchange.github.io/docs/inverse/#t-myposition
    '''
    position_response = session_auth.my_position(
        symbol=symbol_id
    )
    # pprint(response['result'])
    for result in position_response['result']:
        side = result['side']

        print("symbol: {}, side: {}, get risk_id: {}".format(
            result['symbol'], side, result['risk_id']
        ))
        current_risk_id = int(result['risk_id'])

        risk_id = min_risk_id
        if current_risk_id == min_risk_id:
            risk_id = max_risk_id

        '''
        Reference: https://bybit-exchange.github.io/docs/inverse/#t-setrisklimit
        '''
        risk_limit_response = session_auth.set_risk_limit(symbol=symbol_id, side=side, risk_id=risk_id)
        print("symbol: {}, side: {}, set risk_id: {}".format(
            symbol_id, side, risk_limit_response['result']['risk_id']
        ))

    print_symbol_leverage(session_auth)
```

Sample output:
```
symbol: UNIUSDT, min_risk_id: 146, max_risk_id: 160
symbol_id: UNIUSDT, leverage_filter:
{'leverage_step': '0.01', 'max_leverage': 25, 'min_leverage': 1}
symbol: UNIUSDT, side: Buy, get risk_id: 146
symbol: UNIUSDT, side: Buy, set risk_id: 160
symbol: UNIUSDT, side: Sell, get risk_id: 146
symbol: UNIUSDT, side: Sell, set risk_id: 160
symbol_id: UNIUSDT, leverage_filter:
{'leverage_step': '0.01', 'max_leverage': 25, 'min_leverage': 1}
```

"max_leverage" seems to be stuck at value of 25 forever, which when looking back at [Query Symbol](https://bybit-exchange.github.io/docs/inverse/#t-querysymbol), it is designated as _public_ instead of _private_ API which makes sense for the misalignment.

Then the applicability of this "max_leverage" value in "leverage_filter" is in question as user cannot rely on this "max_leverage" value as reliable information to trade as it could be in conflict with "max_leverage" in risk limit provided IF the risk ID is set to different value other that lowest risk ID. We know assuming symbol to exercise lowest risk ID is **NOT always guaranteed** as user could set risk limit to other risk ID.

Since "max_leverage" value in "leverage_filter" of [Query Symbol](https://bybit-exchange.github.io/docs/inverse/#t-querysymbol) does not serve any valid use case other than capturing the maximum leverage value of lowest risk ID, do you think it make more sense to remove "max_leverage" entry from "leverage_filter"?

Please feel free to comment if you have other thoughts.

**Comment by dextertd** [comment]
This is not a question for an API wrapper like pybit, but for the API itself. Please ask at https://t.me/BybitAPI

**Comment by viper7882** [comment]
Thanks @dextertd for looking into this matter for us.

The initial thought was to post it to [BybitAPI](https://t.me/BybitAPI) as well but unfortunately we foresee that someone will be asking the Python code to reproduce the issue. Since Telegram is not as conducive Github in terms of posting source code, the natural thinking is to post the issue in Github. Our apology for any inconvenient caused. 

To Pybit users, an issue when using Pybit is an issue with Pybit. How Pybit with deal or escalate to Bybit team or department should be transparent to users. We hope someone in Bybit API team is notified on this issue before you've closed it.

We've put some thoughts about your request and the thinking process now is to carry out BOTH where issue with long code will be reported both in Github and [BybitAPI](https://t.me/BybitAPI).

**Comment by dextertd** [comment]
It may be a problem you can face with pybit, but you could just as easily reproduce it with any other API wrapper. That's why it's an API issue, not a pybit issue. Users of other wrappers in different languages (or even the same language, for CCXT users) are missing out if you post the issue here. The Bybit API Telegram group linked above is the best place for this conversation, as it is filled with users employing all languages.
