### ISSUE TITLE
Unable to get ws kline data

### ISSUE THREAD

**Issue by just-a-normal-human** [verata-veritatis/pybit#9]
Hi! I was trying to get kline data via the perpetual websocket, it connects without error but the responses thereafter are just empty dicts. Don't know if your supporting perpetual klines?
This is the code I'm using:

```
from pybit import WebSocket
endpoint = 'wss://stream.bybit.com/realtime_public'
sub =  'candle.1.BTCUSDT'
ws_unauth = WebSocket(endpoint, subscriptions=sub)

while True:
    try:
        snap=ws_unauth.fetch('candle.1.BTCUSDT')
        pprint(snap)
        sleep(1)
    except: print('-')
```

and this is the response:

```
2020-10-20 18:45:58 - pybit - INFO - Initializing WebSocket.
{}
2020-10-20 18:46:00 - pybit - INFO - Subscription to ['candle.1.BTCUSDT'] successful.
{}
{}
{}
{}
```
It continues without change.

Also the orderbookL2 endpoint is spitting out this:

```
2020-10-20 18:48:57 - websocket - ERROR - error from callback <bound method WebSocket._on_message of <pybit.WebSocket object at 0x7fe3d9c760d0>>: string indices must be integers
```

Thanks in advance and for the awesome library my man!

**Comment by verata-veritatis** [comment]
Yikes. Sorry about that. I'll fix this by the end of today.

**Comment by verata-veritatis** [comment]
> Hi! I was trying to get kline data via the perpetual websocket, it connects without error but the responses thereafter are just empty dicts. Don't know if your supporting perpetual klines?
> This is the code I'm using:
> 
> ```
> from pybit import WebSocket
> endpoint = 'wss://stream.bybit.com/realtime_public'
> sub =  'candle.1.BTCUSDT'
> ws_unauth = WebSocket(endpoint, subscriptions=sub)
> 
> while True:
>     try:
>         snap=ws_unauth.fetch('candle.1.BTCUSDT')
>         pprint(snap)
>         sleep(1)
>     except: print('-')
> ```
> 
> and this is the response:
> 
> ```
> 2020-10-20 18:45:58 - pybit - INFO - Initializing WebSocket.
> {}
> 2020-10-20 18:46:00 - pybit - INFO - Subscription to ['candle.1.BTCUSDT'] successful.
> {}
> {}
> {}
> {}
> ```
> 
> It continues without change.
> 
> Also the orderbookL2 endpoint is spitting out this:
> 
> ```
> 2020-10-20 18:48:57 - websocket - ERROR - error from callback <bound method WebSocket._on_message of <pybit.WebSocket object at 0x7fe3d9c760d0>>: string indices must be integers
> ```
> 
> Thanks in advance and for the awesome library my man!

Hey, sorry it took a while. I've been doing update after update here for the release candidate and will post a new release within the next week.

Couple notes about your issue here:
- From the docstring of WebSocket, it states to use a list of subscriptions, rather than a single subscription in a string. Essentially, you would be doing `['candle.1.BTCUSD']` rather than `candle.1.BTCUSD`.
- I have just added `candle` to the next release candidate.
- `pybit` will now handle string arguments for subscription and will automatically convert them to a list.

```python
        # Check if subscriptions is a list.
        if isinstance(self.subscriptions, str):
            self.subscriptions = [self.subscriptions]
```

**Comment by verata-veritatis** [comment]
Added `candle` to monitored streams.
https://github.com/verata-veritatis/pybit/commit/aa3311c11a7fbd7d24b02eabeb0243cd7fa6ac02
